config/routes.rb
Rails.application.routes.draw do

  resources :order_products, only: [:create]

  resources :products,only: [:new,:create,:show] do
  	resources :product_posts, only: [:create,:destroy]
    resources :order_products, only: [:new,:edit,:confirm,:done,:show,:create]
  end
  resources :questions, only: [:show,:new,:edit,:create,:update,:destroy] do
  	resource :answers, only: [:edit,:create,:update,:destroy]
  end
  devise_for :users,path:'',path_names: {sign_in:'login',sign_up:'up'}
  root 'tops#top'
  get 'index',to:'tops#index'
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :user
	belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
	belongs_to :product
	belongs_to :user
	enum payment: {クレカ:0,銀行:1}
end

app/models/product.rb
class Product < ApplicationRecord
	attachment :product_image
	has_many :product_posts
	has_many :order_products
end

app/models/product_post.rb
class ProductPost < ApplicationRecord
	attachment :post_image
	belongs_to :user
	belongs_to :product
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
	has_many :answers,dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :questions
  has_many :answers
  has_many :product_posts
  has_many :order_products
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def edit
  end

  def create
  	@question = Question.find(params[:question_id])
  	@answer = @question.answers.new(answer_params)
  	@answer.user_id = current_user.id
  	@answer.save
  	redirect_back fallback_location: @question
  end

  def update
    @answer = Answer.find(params[:question_id])
    @answer.user_id = current_user.id
    @answer.update(answer_params)
  end
  def destroy
    @answer = Answer.find(params[:question_id])
    @answer.user_id = current_user.id
    @answer.destroy
    redirect_back fallback_location: @question
  end

  private
  def answer_params
  	params.require(:answer).permit(:answer_comment)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!,except: :top

end

app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
	def new
		
	end
  def edit
  end

  def confirm

  end

  def done
  end

  def show
  	
  end
  def create
  	@product = Product.find(params[:product_id])
  	@order_product = @product.order_products.new(order_product_params)
  	@order_product.user_id = current_user.id

  	@order_product.save

  end

  private 

  def order_product_params
  	params.require(:order_product).permit(:total_price,:payment)
  end
end

app/controllers/product_posts_controller.rb
class ProductPostsController < ApplicationController

	def create
		@product = Product.find(params[:product_id])
		@product_post = @product.product_posts.new(product_post_params)
		@product_post.user_id = current_user.id
		@product_post.save
		redirect_back fallback_location: @product
	end

	def destroy
		@product_post = ProductPost.find(params[:product_id])
		@product_post.user_id = current_user.id
		@product_post.destroy
		redirect_back fallback_location: @product
	end
	private
	def product_post_params
		params.require(:product_post).permit(:post_title,:post_comment,:post_image)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
  end
  def show
  	@product = Product.find(params[:id])
  	@product_posts = @product.product_posts.all
  end
  def create
  	@product = Product.new(product_params)
  	@product.save
  	redirect_back fallback_location: @product
  end
  private
  def product_params
  	params.require(:product).permit(:name,:price,:introduction,:product_image)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
  	@question = Question.find(params[:id])
    @answers = @question.answers.all
  end

  def new
  	
  end

  def edit
    
  end
  def create
  	@question =Question.new(question_params)
  	@question.user_id = current_user.id
  	@question.save
  	redirect_to "/"
  end

  def update
    @question = Question.find(params[:id])
    @question.user_id = current_user.id
    @question.update(question_params)
    
   
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
  end

  private
  def question_params
  	params.require(:question).permit(:title,:question_comment,:user_id)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def top

  end
  
  def index
  	@products = Product.all
  	@questions = Question.all
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_products_helper.rb
module OrderProductsHelper
end

app/helpers/product_posts_helper.rb
module ProductPostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/answers/edit.html.erb
<h1>回答する</h1>

<%=form_with model: Answer.find(params[:question_id]),url: question_answers_path, local: true do |f| %>
	<div><%= f.text_area :answer_comment %></div>
	<div><%= f.submit%></div>
<% end %>

app/views/order_products/check.html.erb
<h1>OrderProducts#check</h1>
<p>Find me in app/views/order_products/check.html.erb</p>

app/views/order_products/done.html.erb
<h1>OrderProducts#done</h1>
<p>Find me in app/views/order_products/done.html.erb</p>

app/views/order_products/edit.html.erb
<h1>OrderProducts#edit</h1>
<p>Find me in app/views/order_products/edit.html.erb</p>

app/views/order_products/new.html.erb
<h1>入力画面</h1>

<%= form_with model: OrderProduct.new, url:  "/order_products",local: :true do |f| %>
	<div><%=f.radio_button :payment,(:クレカ) %></div>
	<div><%=f.radio_button :payment,(:銀行) %></div>
	<div><%=f.submit %></div>
<% end%>

app/views/order_products/show.html.erb
<h1>入力画面</h1>
<h1>商品名</h1>
<div><%= @product.name %></div>
<div><%= image_tag attachment_url(@product, :product_image, :fill, 300, 300) %></div>
<div><strong>商品説明</strong></div>
<div><%= @product.introduction %></div>
<%= @product.name %>
<%= form_with model: OrderProduct.new,url:  "/products/#{@product.id}/order_products",local: :true do |f| %>
	<div><%=f.radio_button :payment,(:クレカ) %></div>
	<div><%=f.radio_button :payment,(:銀行) %></div>
	<div><%=f.submit %></div>
<% end%>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>
<%= form_with model: Product.new, local: :true do |f|%>
	<div><%=f.label :商品画像%></div>
	<div><%= f.attachment_field :product_image %></div>
	<div><%=f.label :商品名%></div>
	<div><%=f.text_field :name%></div>
	<div><%=f.label :商品説明%></div>
	<div><%= f.text_area :introduction%></div>
	<div><%= f.submit%></div>
<% end %>

app/views/products/show.html.erb
<h1>商品名</h1>
<div><%= @product.name %></div>
<div><%= image_tag attachment_url(@product, :product_image, :fill, 300, 300) %></div>
<div><strong>商品説明</strong></div>
<div><%= @product.introduction %></div>
<%= link_to '購入へ進む', new_product_order_product_path(@product.id)%>

<%= form_with model: OrderProduct.new, url:  "/products/#{@product.id}/order_products",local: :true do |f| %>
	<div><%=f.radio_button :payment,(:クレカ) %></div>
	<div><%=f.radio_button :payment,(:銀行) %></div>
	
	<div><%=f.submit %></div>
<% end%>

<h1>投稿する</h1>
<%=form_with model: ProductPost.new,url: "/products/#{@product.id}/product_posts" ,local: :true do |f| %>
	<div><%= f.label :タイトル %></div>
	<div><%= f.text_field :post_title %></div>
	<div><%= f.label :投稿内容%></div>
	<div><%= f.text_area :post_comment %></div>
	<div><%= f.label :画像%></div>
	<div><%= f.attachment_field :post_image %></div>
	<div><%= f.submit %></div>
<% end %>

<% @product_posts.each do |p|%>
	<div><strong>タイトル</strong></div>
	<div><%= p.post_title%></div>
	<div><strong>投稿内容</strong></div>
	<div><%= p.post_comment%></div>
	<div><%= link_to :削除,product_product_post_path(p.id),method: :delete%></div>
<% end %>

app/views/questions/edit.html.erb
<h2>質問を修正する</h2>
<%=form_with model: Question.find(params[:id]), local: true do |f| %>
	<div><%= f.label :質問%></div>
	<div><%= f.text_field :title%></div>
	<div><%= f.label :内容%></div>
	<div><%= f.text_area :question_comment %></div>
	<div><%= f.submit%></div>
<% end %>

app/views/questions/new.html.erb
<h1>質問する</h1>
<p>Find me in app/views/questions/new.html.erb</p>

<%=form_with model: Question.new, local: true do |f| %>
	<div><%= f.label :質問%></div>
	<div><%= f.text_field :title%></div>
	<div><%= f.label :内容%></div>
	<div><%= f.text_area :question_comment %></div>
	<div><%= f.submit%></div>
<% end %>

app/views/questions/show.html.erb
<h1>質問</h1>
<%= @question.title %>
<h1>内容</h1>
<%= @question.question_comment %>
<%= link_to "修正する",edit_question_path %>

<h1>回答する</h1>
<%=form_with model: Answer.new,url: "/questions/#{@question.id}/answers", local: true do |f| %>
	<div><%= f.text_area :answer_comment %></div>
	<div><%= f.submit%></div>
<% end %>


<% @question.answers.all.each do |a|%>
	<div><%=a.answer_comment%></div>
	<%= link_to "修正する", edit_question_answers_path(a.id) %>
	<%= link_to :削除, "/questions/#{a.id}/answers",method: :delete %>
<% end %>

app/views/tops/index.html.erb
<div>
	<% @products.each do |p| %>
		商品名
	<%= link_to p.name, product_path(p.id) %>
	<%= link_to product_path(p.id) do %>
	<%= image_tag attachment_url(p, :product_image, :fill, 30, 30) %>
	<% end %>
	<%end%>
</div>

<div>
	<% @questions.each do |q| %>
		質問
	<%=link_to q.title,question_path(q.id) %>
	<%= link_to :削除, "/questions/#{q.id}",method: :delete %>
	<%end%>
</div>